import {
	LazyEl,
	LazyIframe,
	LazyImg,
	LazyModule,
	LazyVideo,
	LazyWrapper,
} from "react-vanilla-lazyload";
import { Loader } from "../components/Loader.tsx";
import WallPaper from "../components/WallPaper.tsx";

export default function Demo() {
	return (
		<LazyWrapper>
			<WallPaper />
			<LazyImg
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-01.webp"
				}
				className="demo-item first"
				alt="random"
				title="random"
				width={220}
				height={280}
				onLoad={() => {
					console.log("first lazy-image Loaded");
				}}
			/>
			<LazyImg
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-02.webp"
				}
				srcSet="https://verlok.github.io/vanilla-lazyload/demos/images/440x560-02.webp 400w,https://verlok.github.io/vanilla-lazyload/demos/images/440x560-02.webp 800w"
				dataSizes="100w"
				width={220}
				height={280}
				alt="random"
				className={"demo-item"}
			/>
			<LazyImg
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-03.webp"
				}
				alt="random"
				width={220}
				height={280}
				className={"demo-item"}
			/>
			<LazyImg
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-04.webp"
				}
				alt="random"
				width={220}
				height={280}
				className={"demo-item"}
			/>
			<LazyImg
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-04.webp"
				}
				alt="random"
				width={220}
				height={280}
				className={"demo-item"}
			/>
			<LazyImg
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-05.webp"
				}
				alt="random"
				width={220}
				height={280}
				className={"demo-item"}
			/>
			<LazyImg
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-06.webp"
				}
				alt="random"
				width={220}
				height={280}
				className={"demo-item"}
			/>
			<LazyVideo
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/videos/1920x1080-01.mp4"
				}
				className={"demo-item"}
				width={220}
				height={280}
				poster={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-01.webp"
				}
				controls={true}
			/>
			<LazyVideo
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/videos/1920x1080-02.mp4"
				}
				poster={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-02.webp"
				}
				className={"demo-item"}
				muted
				playsInline
				autoPlay
				width={220}
				height={280}
				controls={false}
			/>
			<LazyImg
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-07.webp"
				}
				className={"demo-item"}
				width={220}
				height={280}
				alt="random"
			/>
			<LazyImg
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-08.webp"
				}
				className={"demo-item"}
				width={220}
				height={280}
				alt="random"
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-09.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyIframe
				className={"demo-item"}
				src={"https://verlok.github.io/vanilla-lazyload/demos/iframes/i01.html"}
				width={500}
				height={500}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-10.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyModule
				className={"demo-item"}
				component={import("../components/Component.tsx")}
				loader={<Loader />}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-11.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-12.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-13.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyEl
				className={"demo-item"}
				bg={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-01.webp"
				}
				title={"asd"}
				style={{
					width: 500,
					height: 500,
					backgroundImage:
						"url(https://verlok.github.io/vanilla-lazyload/demos/images/440x560-01.webp)",
				}}
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-14.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-15.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-16.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-17.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-18.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-19.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-20.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-21.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-22.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-23.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-24.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-25.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-26.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-27.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-28.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-29.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-30.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-31.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-32.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-33.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-34.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-35.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-36.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-37.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-38.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-39.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-40.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-41.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-42.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-43.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-44.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-45.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-46.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-47.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-48.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-49.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
			<LazyImg
				className={"demo-item"}
				src={
					"https://verlok.github.io/vanilla-lazyload/demos/images/440x560-50.webp"
				}
				alt="random"
				width={220}
				height={280}
			/>
		</LazyWrapper>
	);
}
